version: "2"

services:
  nodeapp:
    container_name: nodeapp
    build: .
    ports:
      - "2020:2020"
  varnish:
    build: ./varnish
    container_name: varnish
    ports:
      - "3000:80"
    depends_on:
      - nodeapp



   
      
